// GENERATED by `pnpm tokens:generate` from tokens.css: do not edit by hand.
// Read-only token values for TypeScript consumers (OG images, charts, canvas).

export const tokens = {
  "color": {
    "brand50": "#eff4ff",
    "brand100": "#dbe6fe",
    "brand200": "#bfd3fe",
    "brand300": "#93b4fd",
    "brand400": "#608bfa",
    "brand500": "#3b65f5",
    "brand600": "#2546ea",
    "brand700": "#1d35d7",
    "brand800": "#1e2eae",
    "brand900": "#1e2d89",
    "brand950": "#171e53",
    "neutral0": "#ffffff",
    "neutral50": "#f8fafc",
    "neutral100": "#f1f5f9",
    "neutral200": "#e2e8f0",
    "neutral300": "#cbd5e1",
    "neutral400": "#94a3b8",
    "neutral500": "#64748b",
    "neutral600": "#475569",
    "neutral700": "#334155",
    "neutral800": "#1e293b",
    "neutral900": "#0f172a",
    "neutral950": "#020617",
    "green600": "#15803d",
    "amber600": "#b45309",
    "red600": "#b91c1c",
    "background": "#ffffff",
    "foreground": "#0f172a",
    "surface": "#f8fafc",
    "surfaceMuted": "#f1f5f9",
    "mutedForeground": "#475569",
    "border": "#e2e8f0",
    "primary": "#2546ea",
    "primaryHover": "#1d35d7",
    "primaryForeground": "#ffffff",
    "accent": "#eff4ff",
    "accentForeground": "#1e2eae",
    "inverse": "#171e53",
    "inverseForeground": "#ffffff",
    "success": "#15803d",
    "warning": "#b45309",
    "danger": "#b91c1c",
    "focusRing": "#3b65f5",
    "overlay": "rgb(2 6 23 / 0.6)"
  },
  "font": {
    "heading": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif",
    "body": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif",
    "mono": "var(--font-family-mono), ui-monospace, monospace"
  },
  "type": {
    "display": {
      "size": "clamp(2.75rem, 1.6rem + 4.6vw, 5rem)",
      "lineHeight": "1.02",
      "letterSpacing": "-0.035em",
      "weight": "800",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h1": {
      "size": "clamp(2.25rem, 1.6rem + 2.6vw, 3.5rem)",
      "lineHeight": "1.08",
      "letterSpacing": "-0.03em",
      "weight": "800",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h2": {
      "size": "clamp(1.75rem, 1.35rem + 1.6vw, 2.5rem)",
      "lineHeight": "1.15",
      "letterSpacing": "-0.025em",
      "weight": "700",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h3": {
      "size": "clamp(1.375rem, 1.2rem + 0.7vw, 1.75rem)",
      "lineHeight": "1.25",
      "letterSpacing": "-0.015em",
      "weight": "700",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h4": {
      "size": "1.25rem",
      "lineHeight": "1.35",
      "letterSpacing": "-0.01em",
      "weight": "650",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h5": {
      "size": "1.125rem",
      "lineHeight": "1.4",
      "letterSpacing": "0",
      "weight": "650",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "h6": {
      "size": "1rem",
      "lineHeight": "1.45",
      "letterSpacing": "0",
      "weight": "650",
      "family": "var(--font-family-heading)), ui-sans-serif, system-ui, sans-serif"
    },
    "lead": {
      "size": "clamp(1.125rem, 1.05rem + 0.35vw, 1.3125rem)",
      "lineHeight": "1.6",
      "letterSpacing": "-0.005em",
      "weight": "400",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "bodyLg": {
      "size": "1.125rem",
      "lineHeight": "1.7",
      "letterSpacing": "0",
      "weight": "400",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "body": {
      "size": "1rem",
      "lineHeight": "1.65",
      "letterSpacing": "0",
      "weight": "400",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "bodySm": {
      "size": "0.875rem",
      "lineHeight": "1.55",
      "letterSpacing": "0",
      "weight": "400",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "caption": {
      "size": "0.8125rem",
      "lineHeight": "1.45",
      "letterSpacing": "0.005em",
      "weight": "400",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "overline": {
      "size": "0.8125rem",
      "lineHeight": "1.3",
      "letterSpacing": "0.12em",
      "weight": "700",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "label": {
      "size": "0.875rem",
      "lineHeight": "1.3",
      "letterSpacing": "0.01em",
      "weight": "600",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "button": {
      "size": "0.9375rem",
      "lineHeight": "1",
      "letterSpacing": "0.005em",
      "weight": "650",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    },
    "nav": {
      "size": "0.9375rem",
      "lineHeight": "1.2",
      "letterSpacing": "0",
      "weight": "550",
      "family": "var(--font-family-body), ui-sans-serif, system-ui, sans-serif"
    }
  },
  "spacing": {
    "gutter": "clamp(1rem, 4vw, 2rem)",
    "section": "clamp(3.5rem, 8vw, 7rem)",
    "sectionTight": "clamp(2.5rem, 5vw, 4rem)",
    "stack": "clamp(1.5rem, 3vw, 2.5rem)"
  },
  "container": {
    "content": "72rem",
    "wide": "80rem",
    "prose": "42rem"
  },
  "breakpoint": {
    "sm": "40rem",
    "md": "48rem",
    "lg": "64rem",
    "xl": "80rem"
  },
  "radius": {
    "sm": "0.375rem",
    "md": "0.625rem",
    "lg": "1rem",
    "xl": "1.5rem",
    "full": "9999px"
  },
  "shadow": {
    "sm": "0 1px 2px rgb(15 23 42 / 0.06)",
    "md": "0 8px 24px -8px rgb(15 23 42 / 0.15)",
    "lg": "0 24px 48px -16px rgb(15 23 42 / 0.25)"
  },
  "aspect": {
    "hero": "16 / 10",
    "portrait": "1 / 1",
    "media": "4 / 3"
  },
  "ease": {
    "standard": "cubic-bezier(0.2, 0, 0, 1)",
    "emphasized": "cubic-bezier(0.3, 0, 0, 1.3)"
  },
  "duration": {
    "fast": "120ms",
    "normal": "200ms",
    "slow": "400ms"
  },
  "z": {
    "header": "40",
    "overlay": "50",
    "skipLink": "60"
  }
} as const;

export type Tokens = typeof tokens;
