/** Audit actions. Use these constants; never free-form strings. */
export const AuditAction = {
  LoginSuccess: 'auth.login.success',
  LoginFailure: 'auth.login.failure',
  LoginLocked: 'auth.login.locked',
  Logout: 'auth.logout',
  PasswordChange: 'auth.password.change',
  TwoFactorEnable: 'auth.2fa.enable',
  TwoFactorDisable: 'auth.2fa.disable',
  SessionRevoke: 'auth.session.revoke',
  UserCreate: 'user.create',
  UserUpdate: 'user.update',
  UserDisable: 'user.disable',
  UserEnable: 'user.enable',
  UserDelete: 'user.delete',
  UserPasswordReset: 'user.password.reset',
  UserSessionsRevoke: 'user.sessions.revoke',
  ContentSave: 'content.save',
  ContentRestore: 'content.restore',
  ItemCreate: 'collection.item.create',
  ItemPublish: 'collection.item.publish',
  ItemUnpublish: 'collection.item.unpublish',
  ItemDelete: 'collection.item.delete',
  SeoSave: 'seo.save',
  MediaUpload: 'media.upload',
  MediaDelete: 'media.delete',
  SettingsSave: 'settings.save',
  DatabaseConnect: 'database.connect',
} as const;
export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
