/**
 * Design token tooling (docs/DESIGN_TOKENS.md).
 *
 *   pnpm tokens:generate   tokens.css → src/site/theme/tokens.generated.ts
 *   pnpm tokens:check      fails on raw visual values in src/site and on a stale generated file
 */
import fs from 'node:fs';
import path from 'node:path';

import { groupTokens, parseCustomProperties, resolveTokens } from '@/core/design/token-parse';
import { scanSource, TOKEN_RULE_HELP, type TokenViolation } from '@/core/design/token-scan';

const ROOT = process.cwd();
const THEME_DIR = path.join(ROOT, 'src', 'site', 'theme');
const TOKENS_CSS = path.join(THEME_DIR, 'tokens.css');
const GENERATED = path.join(THEME_DIR, 'tokens.generated.ts');
const SCAN_DIRS = [path.join(ROOT, 'src', 'site'), path.join(ROOT, 'src', 'app', '(site)')];
const SCAN_EXTENSIONS = /\.(tsx?|jsx?|css|mdx?)$/;

function renderGenerated(): string {
  const tokens = groupTokens(
    resolveTokens(parseCustomProperties(fs.readFileSync(TOKENS_CSS, 'utf8'))),
  );
  return [
    '// GENERATED by `pnpm tokens:generate` from tokens.css: do not edit by hand.',
    '// Read-only token values for TypeScript consumers (OG images, charts, canvas).',
    '',
    `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`,
    '',
    'export type Tokens = typeof tokens;',
    '',
  ].join('\n');
}

function listFiles(dir: string): string[] {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir, { recursive: true, encoding: 'utf8' })
    .map((file) => path.join(dir, file))
    .filter((file) => SCAN_EXTENSIONS.test(file) && !file.startsWith(THEME_DIR + path.sep));
}

function check(): void {
  const violations: TokenViolation[] = SCAN_DIRS.flatMap(listFiles).flatMap((file) =>
    scanSource(path.relative(ROOT, file), fs.readFileSync(file, 'utf8')),
  );
  const stale =
    !fs.existsSync(GENERATED) || fs.readFileSync(GENERATED, 'utf8') !== renderGenerated();

  for (const violation of violations) {
    console.error(`${violation.file}:${violation.line}  [${violation.rule}] ${violation.excerpt}`);
    console.error(`    → ${TOKEN_RULE_HELP[violation.rule]}`);
  }
  if (stale)
    console.error('src/site/theme/tokens.generated.ts is out of date. Run `pnpm tokens:generate`.');
  if (violations.length > 0 || stale) {
    console.error(
      `tokens:check failed (${violations.length} violation(s)${stale ? ', stale generated tokens' : ''}).`,
    );
    process.exit(1);
  }
  console.info('tokens:check passed: no raw visual values outside src/site/theme.');
}

const command = process.argv[2];
if (command === 'generate') {
  fs.writeFileSync(GENERATED, renderGenerated());
  console.info(`Wrote ${path.relative(ROOT, GENERATED)}`);
} else if (command === 'check') {
  check();
} else {
  console.error('Usage: tsx scripts/tokens.ts <generate|check>');
  process.exit(1);
}
